[package]
name = "diff_growth_2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiddo = "4.2.0"
nannou = "0.19.0"
anyhow = "1"
